name: Build and Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  IMAGE_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:20-bullseye
      
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - name: Checkout app source
        uses: actions/checkout@v3
        
      - name: Set up environment
        run: |
          apt-get update
          apt-get install -y docker.io
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:latest
            network=host
          install: true
          buildkitd-config-inline: |
            [registry."registry.local:5000"]
              http = true
              insecure = true
              
      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            registry.local:5000/task-api:latest
            registry.local:5000/task-api:${{ env.IMAGE_TAG }}
