apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-app
spec:
  instances: 3
  imageName: 192.168.64.81:5000/postgresql:16.4
  storage:
    size: 5Gi
  bootstrap:
    initdb:
      database: database
      owner: admin
      secret:
        name: db-secret