# App1 Deployment Configuration
# This file should contain the Kubernetes deployment for App1
# 
# Example structure:
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: app1
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: app1
#   template:
#     metadata:
#       labels:
#         app: app1
#     spec:
#       containers:
#       - name: app1
#         image: your-app1-image:tag
#         ports:
#         - containerPort: 80
#
# Add your App1 deployment configuration here 