# App1 Service Configuration
# This file should contain the Kubernetes service for App1
#
# Example structure:
# apiVersion: v1
# kind: Service
# metadata:
#   name: app1-service
# spec:
#   type: NodePort
#   ports:
#   - port: 80
#     targetPort: 80
#     nodePort: 30003
#   selector:
#     app: app1
#
# Add your App1 service configuration here 