apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-api
  template:
    metadata:
      labels:
        app: task-api
    spec:
      containers:
      - name: task-api
        image: 192.168.64.81:5000/task-api:latest
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          value: postgresql://admin:password123@cluster-app-rw:5432/database
        - name: JWT_SECRET
          value: your_ultra_secure_secret
        - name: APP_HOST
          valueFrom:
            configMapKeyRef:
              name: task-api-config
              key: APP_HOST
        - name: APP_PORT
          valueFrom:
            configMapKeyRef:
              name: task-api-config
              key: APP_PORT