apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  namespace: keycloak
type: Opaque
stringData:
  KC_DB_USERNAME: admin
  KC_DB_PASSWORD: password123
  KC_DB_URL: jdbc:postgresql://cluster-app-rw.database.svc.cluster.local:5432/database