---
- hosts: all
  become: yes
  tasks:
    - name: Install base packages
      apt:
        name: [curl, vim, git, docker.io]
        update_cache: yes
        state: present

- hosts: control
  become: yes
  tasks:
    - name: Install K3s control plane
      shell: curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Get K3s node token
      command: cat /var/lib/rancher/k3s/server/node-token
      register: k3s_token
      changed_when: false

    - name: Save token to temporary file
      copy:
        content: "{{ k3s_token.stdout }}"
        dest: /tmp/k3s_token

- hosts: workers
  become: yes
  tasks:
    - name: Join worker to K3s control plane
      shell: |
        curl -sfL https://get.k3s.io | K3S_URL=https://{{ hostvars['k3s-master'].ansible_host }}:6443 K3S_TOKEN={{ lookup('file','/tmp/k3s_token') }} sh -
      args:
        creates: /usr/local/bin/k3s-agent
