apiVersion: v1
kind: Namespace
metadata:
  name: linkerd-grafana
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: linkerd-grafana
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: grafana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: linkerd-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: registry.local:5000/grafana:9.5.10
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: admin
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: admin
            # Configure Grafana for separate domain
            - name: GF_SERVER_ROOT_URL
              value: "http://grafana.linkerd.local/"
            - name: GF_SERVER_SERVE_FROM_SUB_PATH
              value: "false"
            # Set the domain for proper URL generation
            - name: GF_SERVER_DOMAIN
              value: "grafana.linkerd.local"
            - name: GF_INSTALL_PLUGINS
              value: "grafana-piechart-panel,grafana-clock-panel"
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources
      volumes:
        - name: grafana-storage
          emptyDir: {}
        - name: grafana-datasources
          configMap:
            name: grafana-datasources
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: linkerd-grafana
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.linkerd-viz.svc.cluster.local:9090
        isDefault: true