# App2 Configuration
# This file should contain ConfigMap or Secret configurations for App2
#
# Example structure:
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: app2-config
# data:
#   APP_NAME: "Your App2 Name"
#   APP_VERSION: "1.0.0"
#   ENVIRONMENT: "development"
#
# Add your App2 configuration here 