# App2 Service Configuration
# This file should contain the Kubernetes service for App2
#
# Example structure:
# apiVersion: v1
# kind: Service
# metadata:
#   name: app2-service
# spec:
#   type: NodePort
#   ports:
#   - port: 8080
#     targetPort: 8080
#     nodePort: 30004
#   selector:
#     app: app2
#
# Add your App2 service configuration here 